#services:
#  db:
#    container_name: postgres
#    image: postgres
#    environment:
#      POSTGRES_USER: goodcode
#      POSTGRES_PASSWORD: password
#      PGDATA: /data/postgres
#    volumes:
#      - db:/data/postgres
#    networks:
#      - db
#    ports:
#      - 5332:5432
#    restart: unless-stopped
#
#  takenote_bk:
#    container_name: takenote_bk1
#    build: .
#    ports:
#      - 8080:8080
#    networks:
#      - db
##    restart: unless-stopped
#
#networks:
#  db:
#    driver: bridge
#
#volumes:
#  db: